files updated

diff --git a/.github/workflows/terraform-destroy.yml b/.github/workflows/terraform-destroy.yml
--- a/.github/workflows/terraform-destroy.yml
+++ b/.github/workflows/terraform-destroy.yml
@@ -1,4 +1,4 @@
-# name: 4 )  Terraform Destroy
+# name: 4 ) Terraform Destroy
 
 # on:
 #   workflow_dispatch:
@@ -28,13 +28,18 @@
 #     defaults:
 #       run:
 #         working-directory: ./terraform
+
 #     steps:
 #       - uses: actions/checkout@v4
+
 #       - uses: aws-actions/configure-aws-credentials@v4
 #         with:
 #           role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_OIDC_ROLE_NAME }}
 #           aws-region: ${{ secrets.AWS_REGION }}
 
+#       - uses: hashicorp/setup-terraform@v3
+#         with:
+#           terraform_version: "1.6.x"
 
 #       - name: Download tfvars from S3
 #         run: |
@@ -42,32 +47,27 @@
 #           aws s3 cp "s3://${{ secrets.TERRAFORM_STATE_BUCKET }}/env/${{ github.event.inputs.env }}.tfvars" \
 #                     "env/${{ github.event.inputs.env }}.tfvars"
 
-#       - run: |
-#           mkdir -p env
-#           aws s3 cp "s3://${{ secrets.TERRAFORM_STATE_BUCKET }}/env/${{ github.event.inputs.env }}.tfvars" "env/${{ github.event.inputs.env }}.tfvars"
-#       - uses: hashicorp/setup-terraform@v3
-#         with:
-#           terraform_version: "1.6.x"
 
 #       - name: Terraform init
 #         run: terraform init -reconfigure -input=false
 
-
-#       - name: Workspace select
-#         run: terraform workspace select "${WORKSPACE}" || { echo "::error::Workspace $WORKSPACE does not exist"; exit 1; }
-
+#       - name: Workspace select - will fail if missing
+#         run: |
+#           terraform workspace select "${{ github.event.inputs.env }}" \
+#           || { echo "::error::Workspace ${{ github.event.inputs.env }} does not exist"; exit 1; }
 
 #       - name: Terraform destroy
 #         run: terraform destroy -input=false -var-file="env/${{ github.event.inputs.env }}.tfvars" -auto-approve
 
 #   delete_ecr_image:
 #     runs-on: ubuntu-latest
-#     needs: terraform_destroy
+#     needs: cleanup_workspace
 #     steps:
 #       - uses: aws-actions/configure-aws-credentials@v4
 #         with:
 #           role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_OIDC_ROLE_NAME }}
 #           aws-region: ${{ secrets.AWS_REGION }}
+
 #       - run: |
 #           IMAGE="${{ github.event.inputs.container_image }}"
 #           REPOSITORY=$(printf "%s" "$IMAGE" | cut -d'/' -f2- | cut -d'@' -f1 | cut -d':' -f1)
@@ -77,6 +77,43 @@
 #             ID="imageTag=${IMAGE##*:}"
 #           fi
 #           aws ecr batch-delete-image --repository-name "$REPOSITORY" --image-ids "$ID"
+
+#       - name: Delete ECR repository
+#         run: |
+#           IMAGE="${{ github.event.inputs.container_image }}"
+#           REPOSITORY=$(printf "%s" "$IMAGE" | cut -d'/' -f2- | cut -d'@' -f1 | cut -d':' -f1)
+
+#           aws ecr delete-repository --repository-name "$REPOSITORY" --force || true
+
+
+#   cleanup_workspace:
+#     runs-on: ubuntu-latest
+#     needs: terraform_destroy
+#     defaults:
+#       run:
+#         working-directory: ./terraform
+#     steps:
+#       - uses: actions/checkout@v4
+
+#       - uses: aws-actions/configure-aws-credentials@v4
+#         with:
+#           role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_OIDC_ROLE_NAME }}
+#           aws-region: ${{ secrets.AWS_REGION }}
+
+#       - uses: hashicorp/setup-terraform@v3
+#         with:
+#           terraform_version: "1.6.x"
+
+#       - name: Terraform init (S3 backend)
+#         run: terraform init -reconfigure -input=false
+
+#       - name: Switch to default workspace
+#         run: terraform workspace select default
+
+#       - name: Delete Terraform workspace
+#         run: terraform workspace delete -force "${{ github.event.inputs.env }}"
+#         continue-on-error: true
+
 
 
 name: 4 ) Terraform Destroy
@@ -94,7 +131,7 @@ on:
         type: choice
         options: [dev, prod]
       container_image:
-        description: "Full ECR image URI (e.g. 123456.dkr.ecr.eu-west-1.amazonaws.com/app/service:tag or ...@sha256:...)"
+        description: "Full ECR image URI (e.g. 123456.dkr.ecr.eu-west-1.amazonaws.com/app/service:tag )"
         required: true
         type: string
 
@@ -109,7 +146,6 @@ jobs:
     defaults:
       run:
         working-directory: ./terraform
-
     steps:
       - uses: actions/checkout@v4
 
@@ -124,66 +160,63 @@ jobs:
 
       - name: Download tfvars from S3
         run: |
-          mkdir -p env
+          mkdir -p workspace
           aws s3 cp "s3://${{ secrets.TERRAFORM_STATE_BUCKET }}/env/${{ github.event.inputs.env }}.tfvars" \
-                    "env/${{ github.event.inputs.env }}.tfvars"
+                    "workspace/${{ github.event.inputs.env }}.tfvars"
 
-
-      - name: Terraform init
+      - name: Terraform init (S3 backend)
         run: terraform init -reconfigure -input=false
 
-      - name: Workspace select - will fail if missing
+      - name: Workspace select - fail if missing
         run: |
           terraform workspace select "${{ github.event.inputs.env }}" \
           || { echo "::error::Workspace ${{ github.event.inputs.env }} does not exist"; exit 1; }
 
       - name: Terraform destroy
-        run: terraform destroy -input=false -var-file="env/${{ github.event.inputs.env }}.tfvars" -auto-approve
+        run: terraform destroy -input=false -var-file="workspace/${{ github.event.inputs.env }}.tfvars" -auto-approve
 
-  delete_ecr_image:
+  cleanup_workspace:
     runs-on: ubuntu-latest
     needs: terraform_destroy
+    defaults:
+      run:
+        working-directory: ./terraform
     steps:
+      - uses: actions/checkout@v4
+
       - uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_OIDC_ROLE_NAME }}
           aws-region: ${{ secrets.AWS_REGION }}
 
-      - run: |
-          IMAGE="${{ github.event.inputs.container_image }}"
-          REPOSITORY=$(printf "%s" "$IMAGE" | cut -d'/' -f2- | cut -d'@' -f1 | cut -d':' -f1)
-          if [[ "$IMAGE" == *@* ]]; then
-            ID="imageDigest=${IMAGE##*@}"
-          else
-            ID="imageTag=${IMAGE##*:}"
-          fi
-          aws ecr batch-delete-image --repository-name "$REPOSITORY" --image-ids "$ID"
-
-      - name: Delete ECR repository
-        run: |
-          IMAGE="${{ github.event.inputs.container_image }}"
-          REPOSITORY=$(printf "%s" "$IMAGE" | cut -d'/' -f2- | cut -d'@' -f1 | cut -d':' -f1)
-
-          aws ecr delete-repository --repository-name "$REPOSITORY" --force || true
-
-
-  cleanup_workspace:
-    runs-on: ubuntu-latest
-    needs: terraform_destroy
-    steps:
-      - uses: actions/checkout@v4
       - uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: "1.6.x"
 
-      - name: Terraform init
+      - name: Terraform init (S3 backend)
         run: terraform init -reconfigure -input=false
 
-      - name: Switch to default workspace
+      - name: Switch back to default workspace
         run: terraform workspace select default
 
       - name: Delete Terraform workspace
-        run: |
-          echo "Deleting Terraform workspace: ${{ github.event.inputs.env }}"
-          terraform workspace delete "${{ github.event.inputs.env }}"
+        run: terraform workspace delete -force "${{ github.event.inputs.env }}"
         continue-on-error: true
+
+      - name: Delete saved plan artifact (optional)
+        run: aws s3 rm "s3://${{ secrets.TERRAFORM_STATE_BUCKET }}/plans/${{ github.event.inputs.env }}/tfplan" || true
+
+  delete_ecr_repo:
+      runs-on: ubuntu-latest
+      needs: cleanup_workspace
+      steps:
+      - uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_OIDC_ROLE_NAME }}
+          aws-region: ${{ secrets.AWS_REGION }}
+
+      - name: Delete ECR repository (and all images)
+        run: |
+          IMAGE="${{ github.event.inputs.container_image }}"
+          REPOSITORY=$(printf "%s" "$IMAGE" | cut -d'/' -f2- | cut -d'@' -f1 | cut -d':' -f1)
+          aws ecr delete-repository --repository-name "$REPOSITORY" --force || true
